apiVersion: apps/v1
kind: Deployment
metadata:
  name: getservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getservice
  template:
    metadata:
      labels:
        app: getservice
    spec:
      containers:
        - name: getservice
          image: charulatha24/getservice:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/assignment1

#              value: "mongodb://mongodb-service.default.svc.cluster.local:27017/assignment1"
#              value: mongodb://mongodb:27017/assignment1
---
apiVersion: v1
kind: Service
metadata:
  name: getservice
spec:
  type: NodePort
  selector:
    app: getservice
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008

