apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postservice
  template:
    metadata:
      labels:
        app: postservice
    spec:
      containers:
        - name: postservice
          image: charulatha24/postservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: spring-data-mongodb-uri
                  key: SPRING_DATA_MONGODB_URI
#              value: mongodb://mongodb:27017/mongodb
#              value: "mongodb://mongodb-service.default.svc.cluster.local:27017/assignment1"
#              value: mongodb://mongodb:27017/assignment1
---
apiVersion: v1
kind: Service
metadata:
  name: postservice
spec:
  type: NodePort
  selector:
    app: postservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
